#!/usr/bin/env bash

# News Reader


case $BLOCK_BUTTON in
	1) setsid "$TERMINAL" -e newsboat ;;
	2) setsid newsboat -x reload > /dev/null & exit ;;
	3) pgrep -x dunst > /dev/null && notify-send "<b>📰 News module:</b>
- Shows unread news items
- Shows 🔃 if updating with \`newsup\`
- Left click opens newsboat
- Middle click syncs RSS feeds
<b>Note:</b> Only one instance of newsboat (including updates) may be running at a time." ;;
esac

newsboat -x print-unread | awk '{print $1}'
